name: kam2do
description: ToDo app built using Flutter.
version: 0.0.1
authors:
  - Gaurav Purohit <gauravpurohit409@gmail.com>
  - Tirth Patel <pateltirth454@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.2-pre.54"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  hive:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
