import 'package:flutter_web/material.dart';

const Map<String, MaterialColor> primaryColorFromString = {
  'Indigo': Colors.indigo,
  'Blue': Colors.blue,
  'Green': Colors.green,
  'Red': Colors.red,
  'Yellow': Colors.yellow,
  'Amber': Colors.amber,
  'Pink': Colors.pink,
  'Purple': Colors.purple,
  'Deep Purple': Colors.deepPurple,
  'Orange': Colors.orange,
  'Deep Orange': Colors.deepOrange,
  'Brown': Colors.brown,
  'Light Blue': Colors.lightBlue,
  'Light Green': Colors.lightGreen,
  'Cyan': Colors.cyan,
  'Lime': Colors.lime,
  'Teal': Colors.teal,
};

const Map<String, MaterialAccentColor> accentColorFromString = {
  'Indigo': Colors.indigoAccent,
  'Blue': Colors.blueAccent,
  'Green': Colors.greenAccent,
  'Red': Colors.redAccent,
  'Yellow': Colors.yellowAccent,
  'Amber': Colors.amberAccent,
  'Pink': Colors.pinkAccent,
  'Purple': Colors.purpleAccent,
  'Deep Purple': Colors.deepPurpleAccent,
  'Orange': Colors.orangeAccent,
  'Deep Orange': Colors.deepOrangeAccent,
  'Light Blue': Colors.lightBlueAccent,
  'Light Green': Colors.lightGreenAccent,
  'Cyan': Colors.cyanAccent,
  'Lime': Colors.limeAccent,
  'Teal': Colors.tealAccent,
};