name: kam2do_web
description: ToDo app built using Flutter for web.
version: 0.0.1
authors:
  - Gaurav Purohit <gauravpurohit409@gmail.com>
  - Tirth Patel <pateltirth454@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.6.9
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
